name: "💫 Project Inclusion"
description: "Request including a metadata exporter plugin."
title: "💫 [INCLUSION] - <title>"
labels: ["inclusion"]
assignees:
  - poikilotherm
  - pdurbin
  - qqmyers

body:
  - type: markdown
    attributes:
      value: |
        Thanks for considering adding a metadata exporter plugin!
  - type: textarea
    id: description
    attributes:
      label: What kind of exporter do you want to include?
      description: Please describe your exporter, its features and limitations
      placeholder: What does it do?
      value: "My exporter plugin does ..."
    validations:
      required: true
  - type: input
    id: format
    attributes:
      label: Target Export Data Format/s
      description: What kind of data format/s is exported with your plugin?
      placeholder: ex. JSON, JSON-LD, XML, PDF, ...
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source link
      description: Where does your exporter plugin currently reside? (Some public repository please)
      placeholder: ex. https://github.com/..., https://gitlab.com/..., or other
    validations:
      required: true
  - type: input
    id: download
    attributes:
      label: Download link
      description: Where can people download versions of your plugin? (Skip if yes to transfer below)
      placeholder: ex. https://github.com/...
    validations:
      required: false
  - type: dropdown
    id: donate
    attributes:
      label: Move to GDCC
      description: Would you like to request a transfer to the https://github.com/gdcc umbrella?
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or Zulip nick
    validations:
      required: false
